function [masse, m_TS, J_ges_abtr, wkg_gears, d_Abtriebsrad, b_Abtriebsrad, t_ges, l_ges, h_ges, J_x, J_y, J_z, Kosten_Getriebe, i_max, vzkonst, m_geh, m_Zahnraeder_Wellen, m_korb, M_nenn_em_Steuer, n_nenn_em_Steuer, n_max_em_Steuer, typ_em_Steuer, M_max_Steuer, MaxMotorTrqCurve_w, MaxMotorTrqCurve_M, MaxGeneratorTrqCurve_w, MaxGeneratorTrqCurve_M, MotorEffMap3D, MotorEffMap3D_w, MotorEffMap3D_M, GeneratorEffMap3D, GeneratorEffMap3D_w, GeneratorEffMap3D_M, z1_I, z2_II, z1_III, z2_III, z2_IV, zP_I_II, zP_III_IV, zVTV_1, zVTV_2, zVTV_3, zVTV_4,i12_I, i12_II, i12_III, i12_IV, iVTV_1, iVTV_2, eta12_I, eta12_II, eta12_III, eta12_IV, etaVTV_12, etaVTV_34, Jred_EM_Steuer, m_eTV, m_em_Steuer,Jred_eTV, Jx_eTV, Jy_eTV, Jz_eTV, Jx_em_Steuer, Jy_em_Steuer, Jz_em_Steuer, l_SEM, x_eTV, y_eTV, z_eTV, x_SEM, y_SEM, z_SEM]= ...
                    Getriebe(   n_gears, ...
                                i_gears, ...
                                Maximaldrehmoment, ...
                                Nenndrehmoment, ...
                                EM_n_nenn, ...
                                EM_Aussendurchmesser, ...
                                delta_M, ...
                                TV, ...
                                TS, ...
                                az, ...
                                OD, ...
                                Stkzahl, ...
                                Standort, ...
                                Optimierung_Gesamttopologie, ... 
                                d_TIR, ...
                                Spurweite); 

%% Sources
% Overall-Transmission tool is documented and validated in:
% C. Angerer, M. Felgenhauer, I. Eroglu, M. Zähringer, S. Kalt, und 
% M. Lienkamp, “Scalable Dimension-, Weight- and Cost-Modeling for 
% Components of Electric Vehicle Powertrains,” in International 
% Conference on Electrical Machines and Systems, Seoul, Korea, 2018.
% 
% Designtool is based on "mGear" with Extenstion from theses
% by Vladislav Klass (electric Torque Vectoring), 
% Alexander Tripps (Torque Splitter) and Isaak Eroglu (Costmodel)
%                             
% Designtool  "mGear" is authored by Maximilian Zähringer:
% M. Zähringer, “Erstellung eines analytischen Ersatzmodells für Getriebe 
% von Elektrofahrzeugen,” Bachelorarbeit, Lehrstuhl für Fahrzeugtechnik, 
% Technische Universität München, München, 2018.


                            
%% Getriebeauslegung Zähringer

Optimierung_Getriebe={'Masse'};
vzks; % lade Verzahnungskonstanten 

if n_gears==1
    [l_ges,h_ges,t_ges,masse,J_ges_antr,J_ges_abtr,Fehlerbit,Fehlercode, ...
        d_a1,d_a2,d_a3,d_a4, ...
        b_1,b_3, ...
        z_1,z_2,z_3,z_4, ...
        S_H_12,S_H_34,S_F_12,S_F_34,d_1,d_2,d_3,d_4, ...
        alpha,zeta,d_motor,variante, ...
        gamma_1,gamma_2,gamma_3,gamma_1_B,gamma_2_B, ...
        d_1_g,d_2_g,d_4_g,gamma_3_B, ...
        m_A,m_B,m_C,m_D,m_E,m_F,i_12,i_34, ...
        epsilon_beta_12,epsilon_beta_34,epsilon_alpha_12,epsilon_alpha_34, ...
        ID_A,ID_B,ID_C,ID_D,ID_E,ID_F,neig, ...
        m_z1,m_z23,m_z4,m_korb,m_diff_stange,m_kegelraeder, ...
        m_geh,m_w1,m_w2,m_w4,a_12,a_34,alpha_wt_1,alpha_wt_2, m_TS,m_torque_cost, m_Lagersitz, ...
        M_nenn_em_Steuer, n_nenn_em_Steuer, n_max_em_Steuer, typ_em_Steuer, ...
        M_max_Steuer, MaxMotorTrqCurve_w, MaxMotorTrqCurve_M, MaxGeneratorTrqCurve_w, ...
        MaxGeneratorTrqCurve_M, MotorEffMap3D, MotorEffMap3D_w, MotorEffMap3D_M, ...
        GeneratorEffMap3D, GeneratorEffMap3D_w, GeneratorEffMap3D_M, ...
        z1_I, z2_II, z1_III, z2_III, z2_IV, zP_I_II, zP_III_IV, zVTV_1, zVTV_2, zVTV_3,...
        zVTV_4,i12_I, i12_II, i12_III, i12_IV, iVTV_1, iVTV_2, eta12_I, eta12_II, eta12_III,...
        eta12_IV, etaVTV_12, etaVTV_34, Jred_EM_Steuer, m_eTV, m_em_Steuer,Jred_eTV, Jx_eTV, Jy_eTV,...
        Jz_eTV, Jx_em_Steuer, Jy_em_Steuer, Jz_em_Steuer, l_SEM, x_eTV, y_eTV, z_eTV, x_SEM, y_SEM, z_SEM] = ...
        set_stirnradgetriebe(Maximaldrehmoment, Nenndrehmoment, i_gears, ...
        EM_n_nenn, EM_Aussendurchmesser, delta_M, OD, TV, TS, Optimierung_Getriebe, Optimierung_Gesamttopologie, vzkonst, d_TIR, Spurweite);

    i_Stufen=[  i_12, i_34];
    z_Ritzel=[  z_1, z_3];
            
elseif n_gears==2
    [l_ges,h_ges,t_ges,masse,J_ges_antr_gang_1,J_ges_antr_gang_2,J_ges_abtr_gang_1, ...
        J_ges_abtr_gang_2,Fehlerbit,Fehlercode, ...
        d_a1_1,d_a1_2,d_a2_1,d_a2_2,d_a3,d_a4, ...
        b_1_1,b_1_2,b_3, ...
        z_1_1,z_1_2,z_2_1,z_2_2,z_3,z_4, ...
        S_H_12_1,S_H_12_2,S_H_34,S_F_12_1,S_F_12_2,S_F_34, ...
        d_1_1,d_1_2,d_2_1,d_2_2,d_3,d_4, ...
        alpha,zeta,d_motor,variante, ...
        gamma_1,gamma_2,gamma_3, gamma_1_B,gamma_2_B, ...
        d_1_g,d_2_g,d_4_g, ...
        gamma_3_B, ...
        m_A,m_B,m_C,m_D, m_E,m_F, ...
        i_12_1,i_12_2,i_34, ...
        epsilon_beta_1,epsilon_beta_2, ...
        epsilon_beta_3,epsilon_alpha_1,epsilon_alpha_2,epsilon_alpha_3, ...
        ID_A,ID_B,ID_C,ID_D,ID_E,ID_F, ...
        neig,ax_bauraum_schalt,rad_bauraum_schalt, ...
        m_z1_1,m_z1_2,m_z2_1,m_z2_2,m_z3,m_z4,m_w1,m_w2, ...
        m_korb,m_w4,m_kegelraeder,m_diff_stange,m_geh,...
        alpha_wt_1_1,alpha_wt_1_2,alpha_wt_2, m_TS,m_torque_cost, m_Lagersitz, ...
        M_nenn_em_Steuer, n_nenn_em_Steuer, n_max_em_Steuer, typ_em_Steuer, ...
        M_max_Steuer, MaxMotorTrqCurve_w, MaxMotorTrqCurve_M, MaxGeneratorTrqCurve_w, ...
        MaxGeneratorTrqCurve_M, MotorEffMap3D, MotorEffMap3D_w, MotorEffMap3D_M, ...
        GeneratorEffMap3D, GeneratorEffMap3D_w, GeneratorEffMap3D_M, ...
        z1_I, z2_II, z1_III, z2_III, z2_IV, zP_I_II, zP_III_IV, zVTV_1, zVTV_2, zVTV_3,...
        zVTV_4,i12_I, i12_II, i12_III, i12_IV, iVTV_1, iVTV_2, eta12_I, eta12_II, eta12_III,...
        eta12_IV, etaVTV_12, etaVTV_34, Jred_EM_Steuer, m_eTV, m_em_Steuer,Jred_eTV, Jx_eTV, Jy_eTV,...
        Jz_eTV, Jx_em_Steuer, Jy_em_Steuer, Jz_em_Steuer, l_SEM, x_eTV, y_eTV, z_eTV, x_SEM, y_SEM, z_SEM]  = ...
        two_speed_gear(      Maximaldrehmoment, Nenndrehmoment, i_gears(1), ...
        i_gears(2), EM_n_nenn, EM_Aussendurchmesser, delta_M, OD, ...
        TV, TS, Optimierung_Getriebe, Optimierung_Gesamttopologie, vzkonst, d_TIR, Spurweite);

    i_Stufen=[  i_12_1, i_34;
                i_12_2, i_34];
    z_Ritzel=[  z_1_1, z_3;...
                z_1_2, z_3];
    J_ges_abtr=[J_ges_abtr_gang_1, J_ges_abtr_gang_2];
end

b_Abtriebsrad=b_3;
d_Abtriebsrad=d_4;


%Trägheit
if all(i_gears == 1)
    J_red= 0;
end

%% Wirkunggradberechnung nach seeger
vzks; % lade Verzahnungskonstanten nach Seeger
[wkg_gears]= Wirkungsgradberechnung_Getriebe_konstant(n_gears, i_gears, i_Stufen, z_Ritzel); %Wirkungsgradberechnung nach Seeger

%% Kostenberechnung

if i_gears==1 %kein Getriebe
    Kosten_Getriebe=0;           %Keine Getriebenkosten, wenn Übersetzung gleich 1 ist (in Übereinstimmung mit Ausarbeitung von Seeger)
else
    if n_gears==1 %Einganggetriebe
        m_Zahnraeder_Wellen=        m_z1+m_w1+...                                   % Wellen und räder Welle 1
                                    m_z23+m_w2+...                                  % Wellen und räder Welle 2
                                    m_z4 + m_w4 + m_diff_stange + m_Lagersitz + m_kegelraeder ;    % Wellen und räder Welle 3
    elseif n_gears==2 %Zweiganggetriebe
        m_Zahnraeder_Wellen=        m_z1_1 + m_z1_2 + m_w1 ...              % Wellen und räder Welle 1
                                    + m_z2_1 + m_z2_2+m_z3+m_w2+...         % Wellen und räder Welle 2
                                    m_z4 + m_w4 + m_diff_stange + m_Lagersitz + m_kegelraeder ;  % Wellen und räder Welle 3
    end
    [Kosten_Getriebe, K_Material, K_Anbauteile, K_Fertigung]=Kostenrechnung_Getriebe(az, OD, TV, TS, n_gears, i_gears, m_geh, m_Zahnraeder_Wellen, m_korb, m_torque_cost, m_eTV, Stkzahl, Standort);         %Berechnung der Herstellkosten Von Getriebe/MVS an der VA
end


%% weitere Berechnungen

%Korrektur des Torque-Splitter Gewichtes (Auslegung berechnet nur eine
%Kupplungsseite, da Symmetrisch -> für Gesamtgewicht des TS verdoppeln,
%m_TS ist das Gewicht der Lamellenpakete, Hydraulikeinheit ist in
%Getriebe(setmass) integriert
m_TS=2*m_TS;
%Getriebemaße und Haubtachsenträgheiten
[J_x, J_y, J_z] = TraegheitAchsen_GTR(masse, l_ges, t_ges, h_ges); %[kg m^2]
%Offenes Differential
[~,~,~,~,~, Jx_OD, Jy_OD, Jz_OD] = MasseTraegheit_OD(Maximaldrehmoment, max(i_gears));  %[kg m^2]
i_max = max([i_gears]);


